### ISSUE TITLE
Wrong example for DateTimeZone using System.Text.Json serializer

### ISSUE THREAD

**Issue by dgarciarubio** [micro-elements/MicroElements.Swashbuckle.NodaTime#10]
Currently the example for DateTimeZone seems broken when using the System.Text.Json serializer, it returns an object instead of the id of the timezone.

![image](https://user-images.githubusercontent.com/36249646/75093151-9a877e80-557f-11ea-8792-140d4340e473.png)

The response from the endpoint is properly serialized though, so I don't know whats going on here... Any idea?

**Comment by petriashev** [comment]
Created PR for nodatime.serialization: https://github.com/nodatime/nodatime.serialization/pull/57
var dateTimeZone = dateTimeZoneProvider.GetSystemDefault();
dateTimeZone is CachedDateTimeZone (not DateTimeZone) so Converted does not work

**Comment by petriashev** [comment]
Fixed in https://www.nuget.org/packages/MicroElements.Swashbuckle.NodaTime/4.0.0
