### ISSUE TITLE
Support for Swashbuckle ^4.0.0

### ISSUE THREAD

**Issue by ybeauchamph** [micro-elements/MicroElements.Swashbuckle.NodaTime#4]
I'm getting a runtime error when running with Swashbuckle 4

The error I have:
System.MissingMethodException: 'Method not found: 'Void Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.MapType(System.Func`1<Swashbuckle.AspNetCore.Swagger.Schema>)'.'

The MapType method is in the namespace `Microsoft.Extensions.DependencyInjection`. It's missing from `SwaggerGenOptionsExtensions` and causing the error.

**Comment by petriashev** [comment]
looks like you have other version of swashbuckle.aspnetcore. Can you check references in your web service?

**Comment by ybeauchamph** [comment]
I'm using `Swashbuckle.AspNetCore` version 4.0.1

**Comment by ybeauchamph** [comment]
The MapType method was removed from SwaggerGenOptions in version 4.0.0 of Swashbuckle.AspNetCore and moved to an extension method in another namespace `Microsoft.Extensions.DependencyInjection`.

**Comment by petriashev** [comment]
Sorry I mixed up two projects)))

**Comment by petriashev** [comment]
Closed by https://github.com/micro-elements/MicroElements.Swashbuckle.NodaTime/commit/6e811271cd915f9f60716763302d575ea305a69a
