### ISSUE TITLE
Plans to support Swashbuckle 5.0

### ISSUE THREAD

**Issue by WilliamT-Streamba** [micro-elements/MicroElements.Swashbuckle.NodaTime#5]
Do you have plans to update this to support Swashbuckle 5.0 or know how difficult it would be to update this package to support it?

**Comment by petriashev** [comment]
I can update it to prerelease version

**Comment by ericsampson** [comment]
Thanks!

**Comment by petriashev** [comment]
Sorry for the delay. I will update it soon.

**Comment by rmbl-xD** [comment]
Would be nice if it works with swashbuckle 5.0 :)

**Comment by petriashev** [comment]
There will be also support for new json serializer.
But I do not have much free time (
I have changes on my PC and will push it after some cleanup and test

**Comment by ericsampson** [comment]
Awesome, thanks Alexey!

**Comment by petriashev** [comment]
https://www.nuget.org/packages/MicroElements.Swashbuckle.NodaTime/3.0.0-rc.2
Test it!

**Comment by ericsampson** [comment]
@petriashev I noticed that the release version of swashbuckle 5.0 is out, could you upgrade to that please?
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v5.0.0

**Comment by petriashev** [comment]
Oh my god!!!
Just released lib and again! )))

**Comment by ericsampson** [comment]
:D Sorry!!! :)

**Comment by petriashev** [comment]
package updated

**Comment by petriashev** [comment]
look at https://www.nuget.org/packages/MicroElements.Swashbuckle.NodaTime/3.0.0-rc.4

**Comment by petriashev** [comment]
released
