### ISSUE TITLE
Support System.Text.Json?

### ISSUE THREAD

**Issue by ericsampson** [micro-elements/MicroElements.Swashbuckle.NodaTime#6]
Hi Alexey, would it be possible to release a version targeting Swashbuckle 5.0 that supports System.Text.Json instead of Newtonsoft? 
All the best,
Eric

**Comment by petriashev** [comment]
https://www.nuget.org/packages/MicroElements.Swashbuckle.NodaTime/3.0.0-rc.2
Test it!
