### ISSUE TITLE
Add option to disable examples node in the output

### ISSUE THREAD

**Issue by Romanx** [micro-elements/MicroElements.Swashbuckle.NodaTime#7]
Hi there,

Thanks for the great library supporting the latest versions of swashbuckle. Would it be possible to add a flag to avoid generating the example nodes for the Nodatime types. It seems that APIM has issues with example nodes and so doesn't see the open-api schema as being valid even though it is.

Since it was a small change i'll soon put up a test PR for this. Please feel free to push back or discuss a different approach since this is out of the blue.

Thanks,

**Comment by petriashev** [comment]
Thanks for PR
