### ISSUE TITLE
Support for OffsetDate and OffsetTime types

### ISSUE THREAD

**Issue by dgarciarubio** [micro-elements/MicroElements.Swashbuckle.NodaTime#9]
Any reason why OffsetDate and OffsetTime types are not supported? Maybe not the most useful types from NodaTime, but I found it odd that those are the only ones missing. 

I did a quick test on my [fork](https://github.com/dgarciarubio/MicroElements.Swashbuckle.NodaTime), and they seem to work nicely. Should I create a PR?

![image](https://user-images.githubusercontent.com/36249646/75093063-cf470600-557e-11ea-964d-0348b4b53a97.png)

**Comment by petriashev** [comment]
Sure you can create PR. Thanks

**Comment by dgarciarubio** [comment]
I guess we can close this issue now :)
